name: cli
description: A counter command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.19.0-364.0.dev <3.0.0"

dependencies:
  args: ^2.3.1
  counter_core:
    path: ../core
  riverpod: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
