name: api
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.19.0-364.0.dev <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  counter_core:
    path: ../core
  riverpod: ^2.1.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
