name: web
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.19.0-364.0.dev <3.0.0"

dependencies:
  counter_core:
    path: ../core
  riverpod: ^2.1.1

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0

scripts:
  build:
    - webdev build
    - dart compile js -o ./build/main.dart.js ./web/main.dart
